[package]
name = "strling-performance-runner"
version = "0.1.0"
edition = "2021"
rust-version = "1.75"
license = "Apache-2.0"
publish = false

[workspace]

[dependencies]
serde_json = "1.0"
strling = { path = "../../../../../" }
strling-interop = { path = "../../../../../bindings/interop" }
strling-kernel = { path = "../../../../../core/internal" }
