"""Public Simply request-building facade."""

from STRling.simply.constructors import any_of, capture, group, may, merge
from STRling.simply.lookarounds import (
    ahead,
    behind,
    has,
    has_not,
    not_ahead,
    not_behind,
)
from STRling.simply.pattern import Pattern, STRlingError, lit
from STRling.simply.preview import (
    SIMPLY_PREVIEW_LEGACY_PROTOCOL_VERSION,
    SIMPLY_PREVIEW_PROTOCOL_VERSION,
    SIMPLY_PREVIEW_PROTOCOL_VERSIONS,
    SIMPLY_PREVIEW_STATUS,
    NativeSimplyPreviewTransport,
    SimplyPreviewBuilder,
    SimplyPreviewError,
    SimplyPreviewTransport,
    SimplyPreviewTransportError,
    SimplyPreviewValue,
    default_simply_semantic_options,
    serialize_simply_builder_request,
)
from STRling.simply.sets import (
    between,
    character_set,
    in_chars,
    not_between,
    not_in_chars,
)
from STRling.simply.static import (
    alpha_num,
    bound,
    carriage,
    date_time,
    digit,
    email,
    end,
    hex_digit,
    ip,
    letter,
    lower,
    newline,
    not_alpha_num,
    not_bound,
    not_digit,
    not_hex_digit,
    not_letter,
    not_lower,
    not_newline,
    not_special_char,
    not_upper,
    not_whitespace,
    special_char,
    start,
    tab,
    upper,
    url,
    uuid,
    whitespace,
)
from STRling.simply.stdlib_generated import (
    STDLIB_HELPER_IDS,
    STDLIB_REGISTRY_VERSION,
    STDLIB_SURFACE_SOURCE_SHA256,
    date_time as canonical_date_time,
    email as canonical_email,
    ip as canonical_ip,
    url as canonical_url,
    uuid as canonical_uuid,
)

__all__ = [
    "Pattern",
    "STRlingError",
    "lit",
    "any_of",
    "may",
    "merge",
    "capture",
    "group",
    "ahead",
    "not_ahead",
    "behind",
    "not_behind",
    "has",
    "has_not",
    "between",
    "character_set",
    "not_between",
    "in_chars",
    "not_in_chars",
    "alpha_num",
    "not_alpha_num",
    "special_char",
    "not_special_char",
    "letter",
    "not_letter",
    "upper",
    "not_upper",
    "lower",
    "not_lower",
    "hex_digit",
    "not_hex_digit",
    "digit",
    "not_digit",
    "whitespace",
    "not_whitespace",
    "newline",
    "not_newline",
    "tab",
    "carriage",
    "bound",
    "not_bound",
    "start",
    "end",
    "email",
    "url",
    "uuid",
    "ip",
    "date_time",
    "SIMPLY_PREVIEW_LEGACY_PROTOCOL_VERSION",
    "SIMPLY_PREVIEW_PROTOCOL_VERSION",
    "SIMPLY_PREVIEW_PROTOCOL_VERSIONS",
    "SIMPLY_PREVIEW_STATUS",
    "NativeSimplyPreviewTransport",
    "SimplyPreviewBuilder",
    "SimplyPreviewError",
    "SimplyPreviewTransport",
    "SimplyPreviewTransportError",
    "SimplyPreviewValue",
    "default_simply_semantic_options",
    "serialize_simply_builder_request",
    "STDLIB_HELPER_IDS",
    "STDLIB_REGISTRY_VERSION",
    "STDLIB_SURFACE_SOURCE_SHA256",
    "canonical_date_time",
    "canonical_email",
    "canonical_ip",
    "canonical_url",
    "canonical_uuid",
]
