# frozen_string_literal: true

source 'https://rubygems.org'

# Specify your gem's dependencies in strling.gemspec
gemspec

group :development, :test do
  gem 'rspec', '~> 3.13'
  gem 'rake', '~> 13.0'
end
