/**
 * STRling PCRE2 Emitter - IR to PCRE2 Pattern String
 *
 * This module implements the emitter that transforms STRling's Intermediate
 * Representation (IR) into PCRE2-compatible regex pattern strings. The emitter:
 *   - Converts IR operations to PCRE2 syntax
 *   - Handles proper escaping of metacharacters
 *   - Manages character classes and ranges
 *   - Emits quantifiers, groups, and lookarounds
 *   - Applies regex flags as needed
 *
 * The emitter is the final stage of the compilation pipeline, producing actual
 * regex patterns that can be used with PCRE2-compatible regex engines (which
 * includes most modern regex implementations).
 */

import * as IR from "../core/ir.js";
import { STRlingCompilationError, STRlingWarning } from "../core/errors.js";

// ---- emitter safety guards --------------------------------------------------

/**
 * Default maximum AST/IR nesting depth before the emitter aborts.
 *
 * Deeply nested ASTs translate to deeply nested PCRE2 groups and can
 * exhaust the host stack during recursive emission long before PCRE2
 * itself sees the pattern. The limit is chosen to comfortably exceed
 * any human-authored pattern while still rejecting pathological depths
 * generated by fuzzers or untrusted input.
 *
 * Tests may override this via `emit(ir, flags, { maxDepth: N })`.
 */
export const DEFAULT_MAX_DEPTH = 250;

/**
 * Mutable context threaded through `_emitNode` to track depth, the active
 * lookbehind scope, and accumulated warnings. Kept module-internal so the
 * top-level `emit()` API remains a pure function.
 */
interface EmitContext {
    depth: number;
    maxDepth: number;
    inLookbehind: boolean;
    warnings: STRlingWarning[];
}

function _newContext(maxDepth: number = DEFAULT_MAX_DEPTH): EmitContext {
    return {
        depth: 0,
        maxDepth,
        inLookbehind: false,
        warnings: [],
    };
}

/** True iff a quantifier has an unbounded upper bound (`*`, `+`, `{n,}`). */
function _isUnboundedQuant(q: IR.IRQuant): boolean {
    return q.max === "Inf";
}

/** True iff a quantifier matches a variable number of characters. */
function _isVariableLengthQuant(q: IR.IRQuant): boolean {
    return q.min !== q.max;
}

/**
 * Recursively check whether an IR subtree has a fixed character length
 * (i.e. is safe inside a PCRE2 lookbehind). Returns `true` when the
 * subtree is fixed-length, `false` when any descendant is variable-length.
 *
 * Per PCRE2 semantics, the lookbehind body must consume a single, known
 * number of characters. Quantifiers with `min !== max`, alternations whose
 * branches differ in length, and unbounded repeats all violate this.
 */
function _isFixedLengthBody(node: IR.IROp): boolean {
    if (node instanceof IR.IRQuant) {
        return !_isVariableLengthQuant(node) && _isFixedLengthBody(node.child);
    }
    if (node instanceof IR.IRSeq) {
        return node.parts.every(_isFixedLengthBody);
    }
    if (node instanceof IR.IRAlt) {
        // PCRE2 permits lookbehind alternations only when every branch has
        // the same fixed length. We conservatively require each branch to
        // be fixed-length and leave the per-branch length-equality check to
        // PCRE2 itself, since computing it precisely requires expanding
        // character classes and is out of scope for this guard.
        return node.branches.every(_isFixedLengthBody);
    }
    if (node instanceof IR.IRGroup) {
        return _isFixedLengthBody(node.body);
    }
    if (node instanceof IR.IRLook) {
        // Nested lookarounds consume zero characters; safe inside a lookbehind.
        return true;
    }
    // Lit, Dot, CharClass, Anchor, Backref are all single- or zero-width.
    return true;
}

/**
 * Detect nested unbounded quantifiers (e.g. `(a+)+`) inside an IR subtree.
 * Returns `true` if the subtree of `q.child` contains a directly-reachable
 * unbounded `IRQuant`. "Directly reachable" means via single-child wrappers
 * like `IRGroup` and single-element `IRSeq`, where backtracking can run
 * away exponentially. Conservative: avoids false positives on benign
 * concatenations like `a+b+`.
 */
function _hasNestedUnboundedQuant(child: IR.IROp): boolean {
    if (child instanceof IR.IRQuant) {
        return _isUnboundedQuant(child);
    }
    if (child instanceof IR.IRGroup) {
        return _hasNestedUnboundedQuant(child.body);
    }
    if (child instanceof IR.IRSeq && child.parts.length === 1) {
        return _hasNestedUnboundedQuant(child.parts[0]);
    }
    if (child instanceof IR.IRAlt) {
        return child.branches.some(_hasNestedUnboundedQuant);
    }
    return false;
}

const REDOS_MESSAGE =
    "The pattern contains overlapping alternations or nested unbounded " +
    "quantifiers (e.g., (a+)+). This can lead to catastrophic backtracking " +
    "and exponential CPU spikes. Consider using possessive quantifiers " +
    "(++ or *+) or atomic groups to guarantee execution safety.";

function _pushReDoSWarning(ctx: EmitContext): void {
    if (ctx.warnings.some((w) => w.code === "REDOS_RISK")) return;
    ctx.warnings.push(new STRlingWarning("REDOS_RISK", REDOS_MESSAGE));
}

// ---- helpers ----------------------------------------------------------------

/**
 * Escapes PCRE2 metacharacters in literal strings.
 *
 * Escapes characters that have special meaning in PCRE2 regex syntax when
 * used outside character classes. This ensures literal strings are matched
 * exactly as written.
 *
 * @param s - The literal string to escape.
 * @returns The escaped string safe for use in PCRE2 patterns.
 */
export function _escapeLiteral(s: string): string {
    // These are the characters that Python's re.escape() escapes
    const toEscape = new Set([
        " ",
        "#",
        "$",
        "&",
        "(",
        ")",
        "*",
        "+",
        "-",
        ".",
        "?",
        "[",
        "\\",
        "]",
        "^",
        "{",
        "|",
        "}",
        "~",
    ]);

    let result = "";
    for (const ch of s) {
        if (toEscape.has(ch)) {
            // Don't escape dash (matching Python implementation's post-processing)
            if (ch === "-") {
                result += ch;
            } else {
                result += "\\" + ch;
            }
        } else {
            result += ch;
        }
    }
    return result;
}

export function _escapeClassChar(ch: string): string {
    /**
     * Escape a char for use inside [...] per PCRE2 rules.
     */
    // Inside [], ], \, -, and ^ are special and need escaping for safety
    if (ch === "\\" || ch === "]") {
        return "\\" + ch;
    }
    if (ch === "-") {
        return "\\-";
    }
    if (ch === "^") {
        return "\\^";
    }

    // Handle non-printable chars / whitespace for clarity
    if (ch === "\n") return "\\n";
    if (ch === "\r") return "\\r";
    if (ch === "\t") return "\\t";
    if (ch === "\f") return "\\f";
    if (ch === "\v") return "\\v";

    const code = ch.charCodeAt(0);
    if (code < 32 || (code >= 127 && code <= 159)) {
        return `\\x${code.toString(16).padStart(2, "0")}`;
    }

    // All other characters are literal within []
    return ch;
}

function _emitClass(cc: IR.IRCharClass): string {
    /**
     * Emit a PCRE2 character class. If the class is exactly one shorthand escape
     * (like \d or \p{Lu}), prefer the shorthand (with negation flipping) instead
     * of a bracketed class.
     */
    const items = cc.items;

    // --- Single-item shorthand optimization ---------------------------------
    if (items.length === 1 && items[0] instanceof IR.IRClassEscape) {
        const k = items[0].type; // 'd','D','w','W','s','S','p','P'
        const prop = items[0].property;

        if (["d", "w", "s"].includes(k)) {
            // Flip to uppercase negated forms when the entire class is negated
            if (cc.negated && k === "d") return "\\D";
            if (cc.negated && k === "w") return "\\W";
            if (cc.negated && k === "s") return "\\S";
            return "\\" + k;
        }

        if (["D", "W", "S"].includes(k)) {
            // Already-negated shorthands; flip back if the class itself is negated
            const base = k.toLowerCase();
            return cc.negated ? "\\" + base : "\\" + k;
        }

        if (["p", "P"].includes(k) && prop) {
            // For \p{..}/\P{..}, flip p<->P iff exactly-negated class
            const use = cc.negated !== (k === "P") ? "P" : "p";
            return `\\${use}{${prop}}`;
        }
    }

    // --- General case: build a bracket class --------------------------------
    const parts: string[] = [];
    for (const it of items) {
        if (it instanceof IR.IRClassLiteral) {
            parts.push(_escapeClassChar(it.ch));
        } else if (it instanceof IR.IRClassRange) {
            parts.push(
                `${_escapeClassChar(it.fromCh)}-${_escapeClassChar(it.toCh)}`,
            );
        } else if (it instanceof IR.IRClassEscape) {
            if (["d", "D", "w", "W", "s", "S"].includes(it.type)) {
                parts.push("\\" + it.type);
            } else if (["p", "P"].includes(it.type) && it.property) {
                parts.push(`\\${it.type}{${it.property}}`);
            } else {
                parts.push("\\" + it.type);
            }
        } else {
            throw new Error(`class item ${it.constructor.name}`);
        }
    }

    const inner = parts.join("");
    return `[${cc.negated ? "^" : ""}${inner}]`;
}

function _emitQuantSuffix(
    minv: number,
    maxv: number | string,
    mode: string,
): string {
    /**
     * Emit *, +, ?, {m}, {m,}, {m,n} plus optional lazy/possessive suffix.
     */
    let q: string;
    if (minv === 0 && maxv === "Inf") {
        q = "*";
    } else if (minv === 1 && maxv === "Inf") {
        q = "+";
    } else if (minv === 0 && maxv === 1) {
        q = "?";
    } else if (minv === maxv) {
        q = `{${minv}}`;
    } else if (maxv === "Inf") {
        q = `{${minv},}`;
    } else {
        q = `{${minv},${maxv}}`;
    }

    if (mode === "Lazy") {
        q += "?";
    } else if (mode === "Possessive") {
        q += "+";
    }
    return q;
}

function _needsGroupForQuant(child: IR.IROp): boolean {
    /**
     * Return true if 'child' needs a non-capturing group when quantifying.
     */
    if (
        child instanceof IR.IRCharClass ||
        child instanceof IR.IRDot ||
        child instanceof IR.IRGroup ||
        child instanceof IR.IRBackref ||
        child instanceof IR.IRAnchor
    ) {
        return false;
    }
    if (child instanceof IR.IRLit) {
        return child.value.length > 1;
    }
    if (child instanceof IR.IRAlt || child instanceof IR.IRLook) {
        return true;
    }
    if (child instanceof IR.IRSeq) {
        return child.parts.length > 1;
    }
    return false;
}

function _emitGroupOpen(g: IR.IRGroup): string {
    if (g.atomic) {
        return "(?>";
    }
    if (g.capturing) {
        if (g.name !== null) {
            return `(?<${g.name}>`;
        }
        return "(";
    }
    return "(?:";
}

function _emitNode(
    node: IR.IROp,
    parentKind: string = "",
    ctx: EmitContext = _newContext(),
): string {
    // Depth guard: reject ASTs that would risk host-stack exhaustion before
    // PCRE2 ever sees the pattern. The check runs on entry so the message
    // surfaces the offending depth rather than a native stack overflow.
    ctx.depth += 1;
    try {
        if (ctx.depth > ctx.maxDepth) {
            throw new STRlingCompilationError(
                `Maximum AST depth exceeded (limit: ${ctx.maxDepth}). ` +
                    "This pattern is too deeply nested and risks host stack " +
                    "exhaustion during emission. Refactor the pattern to " +
                    "reduce nesting, or flatten capturing groups where possible.",
                "MAX_DEPTH",
                "pcre2",
            );
        }

        if (node instanceof IR.IRLit) {
            return _escapeLiteral(node.value);
        }

        if (node instanceof IR.IRDot) {
            return ".";
        }

        if (node instanceof IR.IRAnchor) {
            const mapping: { [key: string]: string } = {
                Start: "^",
                End: "$",
                WordBoundary: "\\b",
                NotWordBoundary: "\\B",
                AbsoluteStart: "\\A",
                EndBeforeFinalNewline: "\\Z",
                AbsoluteEnd: "\\z",
            };
            return mapping[node.at] || "";
        }

        if (node instanceof IR.IRBackref) {
            if (node.byName !== null) {
                return `\\k<${node.byName}>`;
            }
            if (node.byIndex !== null) {
                return "\\" + node.byIndex;
            }
            return "";
        }

        if (node instanceof IR.IRCharClass) {
            return _emitClass(node);
        }

        if (node instanceof IR.IRSeq) {
            return node.parts
                .map((p: IR.IROp): string => _emitNode(p, "Seq", ctx))
                .join("");
        }

        if (node instanceof IR.IRAlt) {
            const body: string = node.branches
                .map((b: IR.IROp): string => _emitNode(b, "Alt", ctx))
                .join("|");
            // Alt inside sequence/quant should be grouped
            return ["Seq", "Quant"].includes(parentKind) ? `(?:${body})` : body;
        }

        if (node instanceof IR.IRQuant) {
            // ReDoS guard: only flag when the *outer* quantifier is itself
            // unbounded (e.g. `(a+)+`). A bounded outer like `(a+){0,3}`
            // does not produce exponential backtracking.
            if (
                _isUnboundedQuant(node) &&
                _hasNestedUnboundedQuant(node.child)
            ) {
                _pushReDoSWarning(ctx);
            }

            let childStr: string = _emitNode(node.child, "Quant", ctx);
            if (
                _needsGroupForQuant(node.child) &&
                !(node.child instanceof IR.IRGroup)
            ) {
                childStr = `(?:${childStr})`;
            }
            return childStr + _emitQuantSuffix(node.min, node.max, node.mode);
        }

        if (node instanceof IR.IRGroup) {
            return (
                _emitGroupOpen(node) + _emitNode(node.body, "Group", ctx) + ")"
            );
        }

        if (node instanceof IR.IRLook) {
            // Variable-length lookbehind guard: PCRE2 requires fixed-length
            // lookbehind bodies. Detect the violation here so the user gets
            // a Signpost-pattern error rather than an opaque pcre2_compile()
            // failure surfaced from the runtime.
            if (node.dir === "Behind" && !_isFixedLengthBody(node.body)) {
                throw new STRlingCompilationError(
                    "PCRE2 does not support variable-length lookbehinds. " +
                        "The lookbehind body contains a quantifier that makes " +
                        "its length unpredictable. Rewrite the assertion using " +
                        "a fixed-length range (e.g. `{1,8}` instead of `+`), " +
                        "or restructure the pattern using a Lookahead, or " +
                        "extract the quantified portion outside the assertion.",
                    "VLB_NOT_SUPPORTED",
                    "pcre2",
                );
            }

            const wasInLookbehind = ctx.inLookbehind;
            if (node.dir === "Behind") ctx.inLookbehind = true;
            try {
                let op: string;
                if (node.dir === "Ahead" && !node.neg) {
                    op = "?=";
                } else if (node.dir === "Ahead" && node.neg) {
                    op = "?!";
                } else if (node.dir === "Behind" && !node.neg) {
                    op = "?<=";
                } else {
                    op = "?<!";
                }
                return "(" + op + _emitNode(node.body, "Look", ctx) + ")";
            } finally {
                ctx.inLookbehind = wasInLookbehind;
            }
        }

        throw new Error(`Emitter missing for ${node.constructor.name}`);
    } finally {
        ctx.depth -= 1;
    }
}

function _emitPrefixFromFlags(flags: any): string {
    /**
     * Build the inline prefix form expected by tests, e.g. "(?imx)"
     */
    let letters = "";
    if (flags.ignoreCase) letters += "i";
    if (flags.multiline) letters += "m";
    if (flags.dotAll) letters += "s";
    if (flags.unicode) letters += "u";
    if (flags.extended) letters += "x";
    return letters ? `(?${letters})` : "";
}

/**
 * Optional knobs accepted by `emit` / `emitWithDiagnostics`.
 *
 * - `maxDepth`: override the default AST/IR depth ceiling. Primarily used
 *   by the conformance fixture `tests/conformance/inputs/emitter_edges/`
 *   to provoke the depth guard with a small input.
 */
export interface EmitOptions {
    maxDepth?: number;
}

/**
 * Emit a PCRE2 pattern string from IR.
 *
 * If 'flags' is provided, it can be a plain object or a Flags object with .toDict().
 *
 * Throws `STRlingCompilationError` when an emitter safety guard rejects the
 * IR (variable-length lookbehind, AST depth exceeded). Diagnostic warnings
 * (e.g. `REDOS_RISK`) are silently dropped from this back-compat entry
 * point; callers that need them must use `emitWithDiagnostics`.
 */
export function emit(
    irRoot: IR.IROp,
    flags: any = null,
    options: EmitOptions = {},
): string {
    return emitWithDiagnostics(irRoot, flags, options).pattern;
}

/** Result of `emitWithDiagnostics`: the produced pattern plus any warnings. */
export interface EmitResult {
    pattern: string;
    warnings: STRlingWarning[];
}

/**
 * Like `emit`, but also returns the list of `STRlingWarning`s collected
 * during emission. Used by the conformance test runner and any caller that
 * wants to surface `REDOS_RISK` (or future) warnings to the end user.
 */
export function emitWithDiagnostics(
    irRoot: IR.IROp,
    flags: any = null,
    options: EmitOptions = {},
): EmitResult {
    let flagDict: any = null;
    if (flags !== null) {
        if (typeof flags === "object" && !flags.toDict) {
            flagDict = flags;
        } else if (flags.toDict) {
            flagDict = flags.toDict();
        }
    }

    const ctx = _newContext(options.maxDepth ?? DEFAULT_MAX_DEPTH);
    const prefix = flagDict ? _emitPrefixFromFlags(flagDict) : "";
    const body = _emitNode(irRoot, "", ctx);
    return { pattern: prefix + body, warnings: ctx.warnings };
}
