/**
 * Generated by tooling/stdlib_surfaces.py from the canonical registry.
 * Do not edit; these wrappers only record Simply 1.1 helper identity and parameters.
 */

import type { SimplyPreviewBuilder, SimplyPreviewValue } from "./preview.js";

export const STDLIB_SURFACE_SOURCE_SHA256 = "11cabc4bf1934beabf89ccec5a40d07c0ac38d7d24257437800151e2b6947267" as const;
export const STDLIB_REGISTRY_VERSION = "1.0.0" as const;
export const STDLIB_HELPER_IDS = [
    "stdlib.date_time",
    "stdlib.email",
    "stdlib.ip",
    "stdlib.url",
    "stdlib.uuid",
] as const;

export type StdlibHelperId = (typeof STDLIB_HELPER_IDS)[number];

export function dateTime(
    builder: SimplyPreviewBuilder,
    stepId: string,
): SimplyPreviewValue {
    return builder.stdlibHelper(stepId, "stdlib.date_time", {});
}

export function email(
    builder: SimplyPreviewBuilder,
    stepId: string,
): SimplyPreviewValue {
    return builder.stdlibHelper(stepId, "stdlib.email", {});
}

export function ip(
    builder: SimplyPreviewBuilder,
    stepId: string,
    version: number | null = null,
): SimplyPreviewValue {
    return builder.stdlibHelper(stepId, "stdlib.ip", {
        version,
    });
}

export function url(
    builder: SimplyPreviewBuilder,
    stepId: string,
): SimplyPreviewValue {
    return builder.stdlibHelper(stepId, "stdlib.url", {});
}

export function uuid(
    builder: SimplyPreviewBuilder,
    stepId: string,
    version: number | null = null,
): SimplyPreviewValue {
    return builder.stdlibHelper(stepId, "stdlib.uuid", {
        version,
    });
}
