/**
 * Generated by tooling/stdlib_surfaces.py from the canonical registry.
 * Do not edit; these wrappers only record Simply 1.1 helper identity and parameters.
 */

import type { SimplyPreviewBuilder, SimplyPreviewValue } from "./preview.js";

export const STDLIB_SURFACE_SOURCE_SHA256 = "ad40706e8b65108f737ed7b2ef91c77d4531767c79ea4eaf52e8705c12f3610d" as const;
export const STDLIB_REGISTRY_VERSION = "1.0.0" as const;
export const STDLIB_HELPER_IDS = [
    "stdlib.date_time",
    "stdlib.email",
    "stdlib.ip",
    "stdlib.url",
    "stdlib.uuid",
] as const;

export type StdlibHelperId = (typeof STDLIB_HELPER_IDS)[number];

export function dateTime(
    builder: SimplyPreviewBuilder,
    stepId: string,
): SimplyPreviewValue {
    return builder.stdlibHelper(stepId, "stdlib.date_time", {});
}

export function email(
    builder: SimplyPreviewBuilder,
    stepId: string,
): SimplyPreviewValue {
    return builder.stdlibHelper(stepId, "stdlib.email", {});
}

export function ip(
    builder: SimplyPreviewBuilder,
    stepId: string,
    version: number | null = null,
): SimplyPreviewValue {
    return builder.stdlibHelper(stepId, "stdlib.ip", {
        version,
    });
}

export function url(
    builder: SimplyPreviewBuilder,
    stepId: string,
): SimplyPreviewValue {
    return builder.stdlibHelper(stepId, "stdlib.url", {});
}

export function uuid(
    builder: SimplyPreviewBuilder,
    stepId: string,
    version: number | null = null,
): SimplyPreviewValue {
    return builder.stdlibHelper(stepId, "stdlib.uuid", {
        version,
    });
}
